apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suggestion.fullname" . }}-config
  labels:
    {{- include "suggestion.labels" . | nindent 4 }}
data:
  suggestion-config.yaml: |
    # Suggestion Engine Configuration
    engine:
      max_combinations: {{ .Values.env.MAX_COMBINATIONS | default "1000" }}
      time_budget_ms: {{ .Values.env.TIME_BUDGET_MS | default "5000" }}
      min_combination_size: 2
      max_combination_size: 8
      enable_signature_reduction: true
      enable_early_pruning: true
    
    # Evaluation Configuration
    evaluation:
      safety_threshold: 0.8
      privacy_threshold: 0.7
      context_weight: 0.3
      utility_weight: 0.4
      preference_weight: 0.3
      novelty_bonus: 0.1
      effort_penalty: 0.2
    
    # LLM Configuration
    llm:
      enabled: {{ .Values.env.LLM_ENABLED | default "false" }}
      max_tokens: 1000
      temperature: 0.7
      timeout_seconds: 30
      retry_attempts: 3
    
    # Mobile Integration
    mobile:
      push_notifications_enabled: true
      offline_cache_ttl_hours: 24
      max_devices_per_user: 5
      notification_rate_limit_per_minute: 10
    
    # Security Configuration
    security:
      encryption_enabled: true
      audit_logging_enabled: true
      session_timeout_hours: 24
      max_failed_attempts: 5
      lockout_duration_minutes: 15
    
    # Monitoring Configuration
    monitoring:
      metrics_enabled: true
      tracing_enabled: true
      log_level: {{ .Values.env.LOG_LEVEL | default "INFO" }}
      alert_threshold_response_time_ms: 2000
      alert_threshold_error_rate_percent: 5.0
