{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "suggestion.fullname" . }}-ingress
  labels:
    {{- include "suggestion.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/rate-limit-rules: |
      limit_req_zone $binary_remote_addr zone=suggestion:10m rate=10r/s;
      limit_req zone=suggestion burst=20 nodelay;
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "suggestion.{{ .Values.ingress.domain | default "tethral.ai" }}"
spec:
  tls:
    - hosts:
        - suggestion.{{ .Values.ingress.domain | default "tethral.ai" }}
      secretName: {{ include "suggestion.fullname" . }}-tls
  rules:
    - host: suggestion.{{ .Values.ingress.domain | default "tethral.ai" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "suggestion.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: {{ include "suggestion.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /metrics
            pathType: Exact
            backend:
              service:
                name: {{ include "suggestion.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
