apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suggestion.fullname" . }}-secrets
  labels:
    {{- include "suggestion.labels" . | nindent 4 }}
type: Opaque
data:
  # Encryption key for data encryption/decryption
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  
  # LLM API keys (optional)
  llm-api-key: {{ .Values.secrets.llmApiKey | default "" | b64enc | quote }}
  
  # Push notification credentials
  firebase-credentials: {{ .Values.secrets.firebaseCredentials | default "" | b64enc | quote }}
  apns-key: {{ .Values.secrets.apnsKey | default "" | b64enc | quote }}
  
  # Database credentials (if not using external secret)
  database-password: {{ .Values.secrets.databasePassword | default "" | b64enc | quote }}
  
  # JWT signing key
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  
  # Rate limiting secret
  rate-limit-secret: {{ .Values.secrets.rateLimitSecret | b64enc | quote }}
