apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-api-discovery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-api-discovery
  template:
    metadata:
      labels:
        app: iot-api-discovery
    spec:
      containers:
        - name: api
          image: yourrepo/iot-api-discovery:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: api_token
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: OUTBOUND_ALLOWLIST
              value: "earthquake.usgs.gov,api.weather.gov,api.smartcar.com,fleet-api.prd.vn.cloud.tesla.com"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: iot-api-discovery
spec:
  selector:
    app: iot-api-discovery
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
