image: ghcr.io/tethralai/tetheritall-gateway:latest
imageDigest: ""
imagePullPolicy: IfNotPresent
replicaCount: 2
env:
  API_TOKEN: "change-me"
  REDIS_URL: redis://redis:6379/0
  INTEGRATIONS_BASE_URL: http://integrations:8100
service:
  port: 8001
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8001"
serviceAccountName: gateway-sa
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 70
pdb:
  enabled: true
  minAvailable: 1
canary:
  enabled: false
  weight: 10
