apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
