image: ghcr.io/tethralai/tetheritall-integrations:latest
replicaCount: 2
env:
  REDIS_URL: redis://redis:6379/0
service:
  port: 8100
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8100"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 70
pdb:
  enabled: true
  minAvailable: 1
