{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-secrets
  namespace: {{ .Values.namespace | default "iot" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore | default "eso" }}
  target:
    name: gateway-secrets
  data:
    - secretKey: api_token
      remoteRef:
        key: {{ .Values.externalSecrets.gateway.apiToken.key | default "gateway/api_token" }}
    - secretKey: jwt_secret
      remoteRef:
        key: {{ .Values.externalSecrets.gateway.jwtSecret.key | default "gateway/jwt_secret" }}
    - secretKey: jwks_url
      remoteRef:
        key: {{ .Values.externalSecrets.gateway.jwksUrl.key | default "gateway/jwks_url" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db-url
  namespace: {{ .Values.namespace | default "iot" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore | default "eso" }}
  target:
    name: app-db-url
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.database.url.key | default "app/DATABASE_URL" }}
{{- end }}
