apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: app-high
value: 1000000
globalDefault: false
description: High priority for critical app pods
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: app-standard
value: 10000
globalDefault: true
description: Default priority for app pods
---
apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: {{ .Values.namespace | default "iot" }}
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: {{ .Values.namespace | default "iot" }}
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "100"
