# Global/defaults
namespace: iot
global:
  redisUrl: redis://redis:6379/0
  otelExporter: http://otel-collector.iot.svc.cluster.local:4318

api:
  env:
    REDIS_URL: redis://redis:6379/0
  image: ghcr.io/tethralai/tetheritall-api:latest
  replicaCount: 2

integrations:
  env:
    REDIS_URL: redis://redis:6379/0
  image: ghcr.io/tethralai/tetheritall-integrations:latest
  replicaCount: 2

gateway:
  env:
    API_TOKEN: "change-me"
    REDIS_URL: redis://redis:6379/0
    INTEGRATIONS_BASE_URL: http://integrations.iot.svc.cluster.local:8100
  image: ghcr.io/tethralai/tetheritall-gateway:latest
  replicaCount: 2
