name: iot_discovery_app
description: A comprehensive Flutter application for IoT device discovery and onboarding
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  web_socket_channel: ^2.4.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # Camera & AR
  camera: ^0.10.5+5
  image: ^4.1.3
  image_picker: ^1.0.4
  ar_flutter_plugin: ^0.7.3
  
  # Sensors & Hardware
  sensors_plus: ^3.1.0
  geolocator: ^10.1.0
  nfc_manager: ^3.3.0
  flutter_blue_plus: ^1.20.5
  wifi_scan: ^0.4.0
  
  # Security & Authentication
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Voice & Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Analytics & Monitoring
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_performance: ^0.9.3+8
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.2
  
  # QR Code & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # Charts & Visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^23.2.7
  
  # Animation & Effects
  rive: ^0.12.4
  flutter_staggered_animations: ^1.1.1
  
  # Background Processing
  workmanager: ^0.5.2
  background_fetch: ^1.3.2
  
  # File Management
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  
  # Environment & Configuration
  flutter_dotenv: ^5.1.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7
  
  # Edge & Distributed Processing Dependencies
  # ML & AI
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  
  # Distributed Computing
  web_rtc: ^0.9.47
  socket_io_client: ^2.0.3+1
  
  # Local Protocols
  network_info_plus: ^4.1.0
  connectivity_plus: ^5.0.2
  
  # Edge Storage
  sqflite: ^2.3.0
  drift: ^2.14.0
  
  # Security & Privacy
  pointycastle: ^3.7.3
  
  # Performance
  flutter_performance: ^0.0.2
  
  # Development Tools
  flutter_launcher_icons: ^0.13.1
  
  # Advanced Features
  flutter_isolate: ^1.0.0
  compute: ^1.0.0
  
  # Blockchain & Distributed Systems
  web3dart: ^2.7.2
  bip39: ^1.0.6
  
  # Advanced UI
  flutter_gl: ^0.0.2
  
  # Sensor Fusion
  magnetometer: ^0.0.1
  gyroscope: ^0.0.1
  
  # Edge Communication
  grpc: ^3.2.4
  protobuf: ^3.1.0
  
  # Local APIs
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  
  # Advanced Networking
  http: ^1.1.0
  http_parser: ^4.0.2
  
  # Edge Orchestration
  cron: ^0.5.1
  
  # Performance Monitoring
  vm_service: ^11.10.0
  
  # Advanced Security
  local_auth_android: ^1.0.35
  local_auth_ios: ^1.1.5
  
  # Edge Development
  flutter_driver: ^0.0.0
  integration_test: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
    - assets/models/
    - assets/configs/
    - assets/data/
    - .env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
