namespace: iot
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
