apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: integrations-allow-api
spec:
  podSelector:
    matchLabels:
      app: integrations
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: redis