apiVersion: v1
kind: Service
metadata:
  name: {{ include "integrations.fullname" . }}
  labels:
    app: integrations
spec:
  selector:
    app: integrations
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
