apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app: gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
{{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
        - name: gateway
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: token
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
            - name: INTEGRATIONS_BASE_URL
              value: {{ .Values.env.INTEGRATIONS_BASE_URL | quote }}
