apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-egress-allow
spec:
  podSelector:
    matchLabels:
      app: gateway
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: integrations