apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
