name: CI
on:
  push:
    branches: [ feature/iot-orchestrator ]
  pull_request:
    branches: [ feature/iot-orchestrator ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r iot-api-discovery/requirements.txt
      - name: Run tests
        run: |
          python -m pytest -q iot-api-discovery/tests
  docker:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/tetheritall-api:sha-${{ github.sha }} iot-api-discovery
          docker build -t ghcr.io/${{ github.repository }}/tetheritall-integrations:sha-${{ github.sha }} -f iot-api-discovery/Dockerfile iot-api-discovery
          docker build -t ghcr.io/${{ github.repository }}/tetheritall-gateway:sha-${{ github.sha }} -f iot-api-discovery/Dockerfile iot-api-discovery
      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository }}/tetheritall-api:sha-${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/tetheritall-integrations:sha-${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/tetheritall-gateway:sha-${{ github.sha }}
